### ISSUE TITLE
After upgrading Springboot from 2.7 to 3.1, SSOLITE encountered issues

### ISSUE THREAD

**Issue by developwbperson** [sahara3/ssolite#11]
Hello,

Our project is currently using SSOLITE+Springboot 2.7.8
But when we upgraded Springboot to 3.1.5, there were some issues with SSOlite.

May I ask if you plan to upgrade SSOLITE to support Spring Boot 3.1.5?
If you don't plan to upgrade, how should we make modifications to our code to make it run properly?

**Comment by sahara3** [comment]
I plan to release SSOLite 2.0.x to support Spring Security 6 (Spring Boot 3).

On 2024-03-30, I have released version 2.0.0-rc1 to the Maven Central repository.
Would you like to try this release candidate in your project?

If there are no problems, I will officially release version 2.0.0.

**Comment by developwbperson** [comment]
Hello,

Try 2.0.0 - RC1 and there was no problem.

**Comment by developwbperson** [comment]
Hello,

Try 2.0.0 - RC2 and there was no problem.

**Comment by developwbperson** [comment]
Hello, 

May I ask when will the SSOLITE 2.0.0-GA version be released?

Thanks

**Comment by sahara3** [comment]
Sorry for the late reply.
I released version 2.0.0 on 2024-05-31.
https://central.sonatype.com/artifact/com.github.sahara3/ssolite-core/versions

This is the GA version, and it is the same source as 2.0.0-RC2.
Please use this version for your Spring Boot 3.x application.

**Comment by developwbperson** [comment]
Thank you.
